AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Restock Notification App

Globals:
  Function:
    Timeout: 3

Resources:

  # SNS to send restock text messages to your e-mail
  RestockSns:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: ""
          Protocol: "email"
      TopicName: "RestockSns"

  # The Lambda function to deploy
  RestockListener:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: restock_listener/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt LambdaRole.Arn
      Timeout: 600
      MemorySize: 256
      Environment:
        Variables:
          sns_topic_arn: !Ref RestockSns

  # The role to attach to the Lambda that allows it to use other AWS services
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action: ['sns:*']
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: LambdaRole

  # Runs the RestockListener Lambda function on a schedule
  RestockListenerSchedule:
    Type: AWS::Events::Rule
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "rate(15 minutes)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt RestockListener.Arn
          Id: "RestockListenerV1"
          Input: '{
            "subject": "RESTOCK ALERT!",
            "consumer_key": "",
            "consumer_secret": "",
            "access_token": "",
            "access_token_secret": "",
            "screen_name": "Newegg",
            "search_terms": [
                "restock", "ps5"
            ],
            "special_unicode": [
                128680
            ]
          }'

  # Provides scheduler access to the Lambda
  PermissionForEventsToInvokeRestockListener:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RestockListener
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt RestockListenerSchedule.Arn

Outputs:
  RestockListener:
    Description: "Restock Listener Lambda function"
    Value: !GetAtt RestockListener.Arn
  LambdaRole:
    Description: "Restock Listener Lambda role"
    Value: !GetAtt LambdaRole.Arn
